[package]
name = "eru"
version = "0.1.0"
authors = ["Tomoki Aonuma <uasi@uasi.jp>"]

[dependencies]
clap = "1.0.0"
libc = "0.1.8"
unicode-width = "0.1.1"

[dependencies.ncurses]
version = "5.73.0"
default-features = false  # Disable wide support for OS X
